#!/usr/bin/env bash

set -euo pipefail

curl https://deb.releases.teleport.dev/teleport-pubkey.asc -o /usr/share/keyrings/teleport-archive-keyring.asc

echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] https://deb.releases.teleport.dev/ stable main" \
    > /etc/apt/sources.list.d/teleport.list

apt-get update
apt-get install teleport
