#!/bin/bash

set -eu
set -o pipefail

say() { echo "$@" >&2; }
say_do() { say "$@"; "$@"; }

cd /

useradd -m letsencrypt
chsh -s /bin/bash letsencrypt

git clone --depth 1 https://github.com/lukas2511/letsencrypt.sh.git /opt/letsencryptsh

sudo -u letsencrypt bash <<EOF
    cd ~

    [[ ! -f domains.txt ]] && echo '# example.com www.example.com' >> domains.txt

    [[ ! -f config.sh ]] && cat > config.sh <<'EOT'
#!/usr/bin/env bash

WELLKNOWN="\${BASEDIR}/acme-challenges"
CONTACT_EMAIL=albert@peschar.net
EOT

    mkdir -p acme-challenges

    crontab - <<'EOT'
0 0 1 * * cd \$HOME && /opt/letsencryptsh/letsencrypt.sh -c -f config.sh
EOT
EOF

ln -sfn /home/letsencrypt/certs /etc/ssl/letsencrypt

# Configure nginx (if installed).
if [[ -d /etc/nginx/snippets ]]; then
    cat > /etc/nginx/snippets/letsencrypt.conf <<EOF
location ~ ^/\\.well-known/acme-challenge/(.+)$ {
    alias /home/letsencrypt/acme-challenges/\$1;
}
EOF
fi

if [[ -f /etc/nginx/snippets/common.conf ]]; then
    cat >> /etc/nginx/snippets/common.conf <<EOF

include snippets/letsencrypt.conf;
EOF
fi

# Create letsencrypt_all script.
cat > /usr/local/bin/letsencrypt_all <<EOF
#!/bin/bash
exec sudo -u letsencrypt bash -c 'cd ~ && /opt/letsencryptsh/letsencrypt.sh -c -f config.sh'
EOF
chmod 700 /usr/local/bin/letsencrypt_all
