#!/bin/bash

set -eu
set -o pipefail

say() { echo "$@" >&2; }
say_do() { say "$@"; "$@"; }

cd /

export DEBIAN_FRONTEND=noninteractive

say_do apt-get install -y nginx-full nginx-doc

say_do ufw allow 80/tcp
say_do ufw allow 443/tcp
