#!/bin/bash

set -eu
set -o pipefail

say() { echo "$@" >&2; }
say_do() { say "$@"; "$@"; }

cd /

export DEBIAN_FRONTEND=noninteractive

say_do apt-get -qq install -y nginx-full nginx-doc

say_do ufw allow 80/tcp
say_do ufw allow 443/tcp

cat > /etc/nginx/snippets/common.conf <<'EOF'
location ~ /\.ht {
    return 403;
}
EOF

mv /etc/nginx/sites-available/default{,.example}
cat > /etc/nginx/sites-available/default <<'EOF'
server {
    include snippets/common.conf;

    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /var/www/html;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

systemctl restart nginx
