#!/bin/bash

set -eu
set -o pipefail

say() { echo "$@" >&2; }
say_do() { say "$@"; "$@"; }

cd /

export DEBIAN_FRONTEND=noninteractive

pkgs=(
    php5-cli
    php5-curl
    php5-fpm
    php5-gd
    php5-mysqlnd
)

say_do apt-get -qq install -y "${pkgs[@]}"

# Create user_pool.conf for easy per-user pool configuration.
say_do mkdir -p /etc/php5/fpm/include
cat > /etc/php5/fpm/include/user_pool.conf <<EOF
user = \$pool
group = \$pool
listen = /var/run/php5-fpm/\$pool.sock
listen.owner = www-data
listen.group = www-data
pm = ondemand
pm.max_children = 5
pm.process_idle_timeout = 10s
pm.max_requests = 500
chdir = /
EOF

cat > /etc/php5/fpm/pool.d/user.conf.example <<EOF
[user]
include = /etc/php5/fpm/include/user_pool.conf
EOF

# Configure systemd to create a run-time directory.
say_do mkdir -p /etc/systemd/system/php5-fpm.service.d
cat > /etc/systemd/system/php5-fpm.service.d/RuntimeDirectory.conf <<EOF
[Service]
RuntimeDirectory = php5-fpm
EOF

# Configure PHP
cat > /etc/php5/fpm/conf.d/30-provision.ini <<EOF
short_open_tag = On
upload_max_filesize = 64M
post_max_size = 65M
EOF

# Restart php5-fpm.
say_do systemctl daemon-reload
say_do systemctl restart php5-fpm
