#!/bin/bash

set -eu
set -o pipefail

say() { echo "$@" >&2; }
say_do() { say "$@"; "$@"; }

cd /

if [[ -f /swapfile ]]; then
    say "Please check swap configuration manually."
    say "File already exists: /swapfile"
    exit 1
fi

# Create a swap file.
fallocate -l 2G /swapfile
chmod 600 /swapfile
mkswap /swapfile

# Configure swap.
echo "/swapfile none swap default 0 0" >> /etc/fstab

# Enable swap.
swapon -a
